services:
  kwi-db:
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  kwi-api:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"

    volumes:
      - .:/rs/src/app
      - kwi-cargo-target:/rs/src/app/target
      - kwi-cargo-cache:/usr/local/cargo/registry

volumes:
  kwi-cargo-target:
  kwi-cargo-cache:
